name = "loot-filters-api-v2"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "loot-filters-v2"
database_id = "8ace97e9-d35b-4113-8e8e-3209e9264d37"
migrations_dir = "migrations"

# Environment variables
[vars]
DISCORD_CLIENT_ID = "1411366696979009567"
DISCORD_CLIENT_SECRET = "YdmELTTGY4Ga9ab7C5X3PYBUVu14J70e"
# If you're changing one; you need to change the other
DISCORD_REDIRECT_URI = "https://v2.kaqemeex.net/login/redirect"
DISCORD_LOGIN_URI = "https://discord.com/oauth2/authorize?client_id=1411366696979009567&response_type=code&redirect_uri=https%3A%2F%2Fv2.kaqemeex.net%2Flogin%2Fredirect&scope=identify"

# Cron triggers (optional)
[triggers]
crons = []
